// iching.js — I Ching trigram and hexagram data for the Octaeteris Calendar
// ============================================================================

const trigrams = [
  { octal_value: "0", binary_value: "000", pinyin: "kūn", english_name: "Earth", element: "earth", attribute: "devoted", symbol: "☷" },
  { octal_value: "1", binary_value: "001", pinyin: "gèn", english_name: "Mountain", element: "earth", attribute: "keeping still", symbol: "☶" },
  { octal_value: "2", binary_value: "010", pinyin: "kǎn", english_name: "Water", element: "water", attribute: "abysmal", symbol: "☵" },
  { octal_value: "3", binary_value: "011", pinyin: "xùn", english_name: "Wind", element: "wood", attribute: "penetrating", symbol: "☴" },
  { octal_value: "4", binary_value: "100", pinyin: "zhèn", english_name: "Thunder", element: "wood", attribute: "arousing", symbol: "☳" },
  { octal_value: "5", binary_value: "101", pinyin: "lí", english_name: "Fire", element: "fire", attribute: "light-giving", symbol: "☲" },
  { octal_value: "6", binary_value: "110", pinyin: "duì", english_name: "Lake", element: "metal", attribute: "joyous", symbol: "☱" },
  { octal_value: "7", binary_value: "111", pinyin: "qián", english_name: "Heaven", element: "metal", attribute: "strong", symbol: "☰" },
]

const hexagrams = [
  { octal_pair: "00", binary_value: "000000", fuxi_sequence_number: 64, pinyin: "kūn", english_name: "The Receptive Earth", upper_trigram_pinyin: "kūn", lower_trigram_pinyin: "kūn" },
  { octal_pair: "01", binary_value: "000001", fuxi_sequence_number: 63, pinyin: "bāo", english_name: "Splitting Apart", upper_trigram_pinyin: "kūn", lower_trigram_pinyin: "gèn" },
  { octal_pair: "02", binary_value: "000010", fuxi_sequence_number: 62, pinyin: "bǐ", english_name: "Holding Together", upper_trigram_pinyin: "kūn", lower_trigram_pinyin: "kǎn" },
  { octal_pair: "03", binary_value: "000011", fuxi_sequence_number: 61, pinyin: "guàn", english_name: "Contemplation", upper_trigram_pinyin: "kūn", lower_trigram_pinyin: "xùn" },
  { octal_pair: "04", binary_value: "000100", fuxi_sequence_number: 60, pinyin: "yù", english_name: "Enthusiasm", upper_trigram_pinyin: "kūn", lower_trigram_pinyin: "zhèn" },
  { octal_pair: "05", binary_value: "000101", fuxi_sequence_number: 59, pinyin: "jìn", english_name: "Progress", upper_trigram_pinyin: "kūn", lower_trigram_pinyin: "lí" },
  { octal_pair: "06", binary_value: "000110", fuxi_sequence_number: 58, pinyin: "cuì", english_name: "Gathering Together", upper_trigram_pinyin: "kūn", lower_trigram_pinyin: "duì" },
  { octal_pair: "07", binary_value: "000111", fuxi_sequence_number: 57, pinyin: "pǐ", english_name: "Standstill", upper_trigram_pinyin: "kūn", lower_trigram_pinyin: "qián" },
  { octal_pair: "10", binary_value: "001000", fuxi_sequence_number: 56, pinyin: "qiān", english_name: "Modesty", upper_trigram_pinyin: "gèn", lower_trigram_pinyin: "kūn" },
  { octal_pair: "11", binary_value: "001001", fuxi_sequence_number: 55, pinyin: "gèn", english_name: "The Keeping Still Mountain", upper_trigram_pinyin: "gèn", lower_trigram_pinyin: "gèn" },
  { octal_pair: "12", binary_value: "001010", fuxi_sequence_number: 54, pinyin: "jiǎn", english_name: "Obstruction", upper_trigram_pinyin: "gèn", lower_trigram_pinyin: "kǎn" },
  { octal_pair: "13", binary_value: "001011", fuxi_sequence_number: 53, pinyin: "jiàn", english_name: "Development", upper_trigram_pinyin: "gèn", lower_trigram_pinyin: "xùn" },
  { octal_pair: "14", binary_value: "001100", fuxi_sequence_number: 52, pinyin: "xiǎoguò", english_name: "Small Preponderance", upper_trigram_pinyin: "gèn", lower_trigram_pinyin: "zhèn" },
  { octal_pair: "15", binary_value: "001101", fuxi_sequence_number: 51, pinyin: "lǚ", english_name: "The Wanderer", upper_trigram_pinyin: "gèn", lower_trigram_pinyin: "lí" },
  { octal_pair: "16", binary_value: "001110", fuxi_sequence_number: 50, pinyin: "xián", english_name: "Influence", upper_trigram_pinyin: "gèn", lower_trigram_pinyin: "duì" },
  { octal_pair: "17", binary_value: "001111", fuxi_sequence_number: 49, pinyin: "dùn", english_name: "Retreat", upper_trigram_pinyin: "gèn", lower_trigram_pinyin: "qián" },
  { octal_pair: "20", binary_value: "010000", fuxi_sequence_number: 48, pinyin: "shī", english_name: "The Army", upper_trigram_pinyin: "kǎn", lower_trigram_pinyin: "kūn" },
  { octal_pair: "21", binary_value: "010001", fuxi_sequence_number: 47, pinyin: "méng", english_name: "Youthful Folly", upper_trigram_pinyin: "kǎn", lower_trigram_pinyin: "gèn" },
  { octal_pair: "22", binary_value: "010010", fuxi_sequence_number: 46, pinyin: "kǎn", english_name: "The Abysmal Water", upper_trigram_pinyin: "kǎn", lower_trigram_pinyin: "kǎn" },
  { octal_pair: "23", binary_value: "010011", fuxi_sequence_number: 45, pinyin: "huàn", english_name: "Dispersion", upper_trigram_pinyin: "kǎn", lower_trigram_pinyin: "xùn" },
  { octal_pair: "24", binary_value: "010100", fuxi_sequence_number: 44, pinyin: "jiě", english_name: "Deliverance", upper_trigram_pinyin: "kǎn", lower_trigram_pinyin: "zhèn" },
  { octal_pair: "25", binary_value: "010101", fuxi_sequence_number: 43, pinyin: "wèijì", english_name: "Before Completion", upper_trigram_pinyin: "kǎn", lower_trigram_pinyin: "lí" },
  { octal_pair: "26", binary_value: "010110", fuxi_sequence_number: 42, pinyin: "kùn", english_name: "Oppression", upper_trigram_pinyin: "kǎn", lower_trigram_pinyin: "duì" },
  { octal_pair: "27", binary_value: "010111", fuxi_sequence_number: 41, pinyin: "sòng", english_name: "Conflict", upper_trigram_pinyin: "kǎn", lower_trigram_pinyin: "qián" },
  { octal_pair: "30", binary_value: "011000", fuxi_sequence_number: 40, pinyin: "shēng", english_name: "Pushing Upward", upper_trigram_pinyin: "xùn", lower_trigram_pinyin: "kūn" },
  { octal_pair: "31", binary_value: "011001", fuxi_sequence_number: 39, pinyin: "gǔ", english_name: "Work on the Decayed", upper_trigram_pinyin: "xùn", lower_trigram_pinyin: "gèn" },
  { octal_pair: "32", binary_value: "011010", fuxi_sequence_number: 38, pinyin: "jǐng", english_name: "The Well", upper_trigram_pinyin: "xùn", lower_trigram_pinyin: "kǎn" },
  { octal_pair: "33", binary_value: "011011", fuxi_sequence_number: 37, pinyin: "xùn", english_name: "The Gentle Wind", upper_trigram_pinyin: "xùn", lower_trigram_pinyin: "xùn" },
  { octal_pair: "34", binary_value: "011100", fuxi_sequence_number: 36, pinyin: "héng", english_name: "Duration", upper_trigram_pinyin: "xùn", lower_trigram_pinyin: "zhèn" },
  { octal_pair: "35", binary_value: "011101", fuxi_sequence_number: 35, pinyin: "dǐng", english_name: "The Cauldron", upper_trigram_pinyin: "xùn", lower_trigram_pinyin: "lí" },
  { octal_pair: "36", binary_value: "011110", fuxi_sequence_number: 34, pinyin: "dàguò", english_name: "Great Preponderance", upper_trigram_pinyin: "xùn", lower_trigram_pinyin: "duì" },
  { octal_pair: "37", binary_value: "011111", fuxi_sequence_number: 33, pinyin: "gòu", english_name: "Coming to Meet", upper_trigram_pinyin: "xùn", lower_trigram_pinyin: "qián" },
  { octal_pair: "40", binary_value: "100000", fuxi_sequence_number: 32, pinyin: "fù", english_name: "Return", upper_trigram_pinyin: "zhèn", lower_trigram_pinyin: "kūn" },
  { octal_pair: "41", binary_value: "100001", fuxi_sequence_number: 31, pinyin: "yí", english_name: "Mouth Corners", upper_trigram_pinyin: "zhèn", lower_trigram_pinyin: "gèn" },
  { octal_pair: "42", binary_value: "100010", fuxi_sequence_number: 30, pinyin: "tún", english_name: "Difficulty at the Beginning", upper_trigram_pinyin: "zhèn", lower_trigram_pinyin: "kǎn" },
  { octal_pair: "43", binary_value: "100011", fuxi_sequence_number: 29, pinyin: "yì", english_name: "Increase", upper_trigram_pinyin: "zhèn", lower_trigram_pinyin: "xùn" },
  { octal_pair: "44", binary_value: "100100", fuxi_sequence_number: 28, pinyin: "zhèn", english_name: "The Arousing Thunder", upper_trigram_pinyin: "zhèn", lower_trigram_pinyin: "zhèn" },
  { octal_pair: "45", binary_value: "100101", fuxi_sequence_number: 27, pinyin: "shìhé", english_name: "Biting Through", upper_trigram_pinyin: "zhèn", lower_trigram_pinyin: "lí" },
  { octal_pair: "46", binary_value: "100110", fuxi_sequence_number: 26, pinyin: "suí", english_name: "Following", upper_trigram_pinyin: "zhèn", lower_trigram_pinyin: "duì" },
  { octal_pair: "47", binary_value: "100111", fuxi_sequence_number: 25, pinyin: "wúwàng", english_name: "Innocence", upper_trigram_pinyin: "zhèn", lower_trigram_pinyin: "qián" },
  { octal_pair: "50", binary_value: "101000", fuxi_sequence_number: 24, pinyin: "míngyí", english_name: "Darkening of the Light", upper_trigram_pinyin: "lí", lower_trigram_pinyin: "kūn" },
  { octal_pair: "51", binary_value: "101001", fuxi_sequence_number: 23, pinyin: "bì", english_name: "Grace", upper_trigram_pinyin: "lí", lower_trigram_pinyin: "gèn" },
  { octal_pair: "52", binary_value: "101010", fuxi_sequence_number: 22, pinyin: "jìjì", english_name: "After Completion", upper_trigram_pinyin: "lí", lower_trigram_pinyin: "kǎn" },
  { octal_pair: "53", binary_value: "101011", fuxi_sequence_number: 21, pinyin: "jiārén", english_name: "The Family", upper_trigram_pinyin: "lí", lower_trigram_pinyin: "xùn" },
  { octal_pair: "54", binary_value: "101100", fuxi_sequence_number: 20, pinyin: "fēng", english_name: "Abundance", upper_trigram_pinyin: "lí", lower_trigram_pinyin: "zhèn" },
  { octal_pair: "55", binary_value: "101101", fuxi_sequence_number: 19, pinyin: "lí", english_name: "The Clinging Fire", upper_trigram_pinyin: "lí", lower_trigram_pinyin: "lí" },
  { octal_pair: "56", binary_value: "101110", fuxi_sequence_number: 18, pinyin: "gé", english_name: "Revolution", upper_trigram_pinyin: "lí", lower_trigram_pinyin: "duì" },
  { octal_pair: "57", binary_value: "101111", fuxi_sequence_number: 17, pinyin: "tóngrén", english_name: "Fellowship", upper_trigram_pinyin: "lí", lower_trigram_pinyin: "qián" },
  { octal_pair: "60", binary_value: "110000", fuxi_sequence_number: 16, pinyin: "lín", english_name: "Approach", upper_trigram_pinyin: "duì", lower_trigram_pinyin: "kūn" },
  { octal_pair: "61", binary_value: "110001", fuxi_sequence_number: 15, pinyin: "sǔn", english_name: "Decrease", upper_trigram_pinyin: "duì", lower_trigram_pinyin: "gèn" },
  { octal_pair: "62", binary_value: "110010", fuxi_sequence_number: 14, pinyin: "jié", english_name: "Limitation", upper_trigram_pinyin: "duì", lower_trigram_pinyin: "kǎn" },
  { octal_pair: "63", binary_value: "110011", fuxi_sequence_number: 13, pinyin: "zhōngfú", english_name: "Inner Truth", upper_trigram_pinyin: "duì", lower_trigram_pinyin: "xùn" },
  { octal_pair: "64", binary_value: "110100", fuxi_sequence_number: 12, pinyin: "guīmèi", english_name: "The Marrying Maiden", upper_trigram_pinyin: "duì", lower_trigram_pinyin: "zhèn" },
  { octal_pair: "65", binary_value: "110101", fuxi_sequence_number: 11, pinyin: "kuí", english_name: "Opposition", upper_trigram_pinyin: "duì", lower_trigram_pinyin: "lí" },
  { octal_pair: "66", binary_value: "110110", fuxi_sequence_number: 10, pinyin: "duì", english_name: "The Joyous Lake", upper_trigram_pinyin: "duì", lower_trigram_pinyin: "duì" },
  { octal_pair: "67", binary_value: "110111", fuxi_sequence_number: 9, pinyin: "lǚ", english_name: "Treading", upper_trigram_pinyin: "duì", lower_trigram_pinyin: "qián" },
  { octal_pair: "70", binary_value: "111000", fuxi_sequence_number: 8, pinyin: "tài", english_name: "Peace", upper_trigram_pinyin: "qián", lower_trigram_pinyin: "kūn" },
  { octal_pair: "71", binary_value: "111001", fuxi_sequence_number: 7, pinyin: "dàxù", english_name: "Great Taming", upper_trigram_pinyin: "qián", lower_trigram_pinyin: "gèn" },
  { octal_pair: "72", binary_value: "111010", fuxi_sequence_number: 6, pinyin: "xū", english_name: "Waiting", upper_trigram_pinyin: "qián", lower_trigram_pinyin: "kǎn" },
  { octal_pair: "73", binary_value: "111011", fuxi_sequence_number: 5, pinyin: "xiǎoxù", english_name: "Small Taming", upper_trigram_pinyin: "qián", lower_trigram_pinyin: "xùn" },
  { octal_pair: "74", binary_value: "111100", fuxi_sequence_number: 4, pinyin: "dàzhuàng", english_name: "Great Power", upper_trigram_pinyin: "qián", lower_trigram_pinyin: "zhèn" },
  { octal_pair: "75", binary_value: "111101", fuxi_sequence_number: 3, pinyin: "dàyǒu", english_name: "Great Possession", upper_trigram_pinyin: "qián", lower_trigram_pinyin: "lí" },
  { octal_pair: "76", binary_value: "111110", fuxi_sequence_number: 2, pinyin: "guài", english_name: "Breakthrough", upper_trigram_pinyin: "qián", lower_trigram_pinyin: "duì" },
  { octal_pair: "77", binary_value: "111111", fuxi_sequence_number: 1, pinyin: "qián", english_name: "The Creative Heaven", upper_trigram_pinyin: "qián", lower_trigram_pinyin: "qián" },
]

export { trigrams, hexagrams }
export default { trigrams, hexagrams }
